image: node

before_script:
    - npm ci

cache:
    paths:
        - node_modules/

pages:
    script:
        - npm run generate
        - gzip -k -6 -r public # k - keep org file, 6 - compression level, r - compress each file in folder(recursive)
    artifacts:
        paths:
            - public
    only:
        - master
